/*
 * Copyright DataStax, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'java'
    id 'java-library'
    id 'com.gradleup.shadow' version '9.0.2'
}

apply(plugin: 'idea')

// Force checkstyle and rat to run before test tasks for faster feedback
def codeCheckTasks = task("codeCheckTasks")

tasks.register('copyCodeStyle', Copy) {
    from('ide/idea/codeStyleSettings.xml')
    into('.idea')
}

tasks.idea.dependsOn(tasks.copyCodeStyle)

tasks.register('copyInspections', Copy) {
    from('ide/idea/Project_Default.xml')
    into('.idea/inspectionProfiles')
}
tasks.idea.dependsOn(tasks.copyInspections)

subprojects {
    apply(plugin: 'java-library')
    apply(plugin: 'checkstyle')

    repositories {
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        compileOnly libs.jetbrains.annotations
        testCompileOnly libs.jetbrains.annotations
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of("${project.analyticsJdkLevel}")
        }
    }

    codeCheckTasks.dependsOn(tasks.withType(Checkstyle))
}
