/*
 * Copyright DataStax, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id('java-library')
    id('com.gradleup.shadow')
    id('maven-publish')
}

repositories {
    mavenLocal()
    mavenCentral()
}

def nonJar = configurations.create('nonJar')

configurations.compileClasspath {
    extendsFrom nonJar
}

dependencies {
    add('nonJar', files('../cassandra-four-nine/build/libs/four-zero.jar'))
    add('nonJar', files('../cassandra-four-nine-bridge/build/libs/four-zero-bridge.jar'))
    add('nonJar', files('../cassandra-four-nine-types/build/libs/four-zero-types.jar'))
    add('nonJar', files('../cassandra-analytics-spark-four-nine-converter/build/libs/four-zero-sparksql.jar'))

    add('nonJar', files('../cassandra-five-zero/build/libs/five-zero.jar'))
    add('nonJar', files('../cassandra-five-zero-bridge/build/libs/five-zero-bridge.jar'))
    add('nonJar', files('../cassandra-five-zero-types/build/libs/five-zero-types.jar'))
    add('nonJar', files('../cassandra-analytics-spark-five-zero-converter/build/libs/five-zero-sparksql.jar'))

    implementation ("org.apache.cassandra:cassandra-analytics-core_spark3_${scalaVersion}:${analyticsVersion}") {
        transitive = false
    }
    compileOnly("org.apache.spark:spark-sql_${scalaVersion}:${sparkVersion}")
    compileOnly("org.apache.cassandra:cassandra-analytics-common:${analyticsVersion}")
}

jar {
    enabled = false
}

shadowJar {
    archiveClassifier = ""
    zip64 = true

    dependsOn ':cassandra-four-nine:shadowJar'
    dependsOn ':cassandra-four-nine-bridge:shadowJar'
    dependsOn ':cassandra-four-nine-types:shadowJar'
    dependsOn ':cassandra-analytics-spark-four-nine-converter:shadowJar'

    dependsOn ':cassandra-five-zero:shadowJar'
    dependsOn ':cassandra-five-zero-bridge:shadowJar'
    dependsOn ':cassandra-five-zero-types:shadowJar'
    dependsOn ':cassandra-analytics-spark-five-zero-converter:shadowJar'

    exclude 'bridges/four-zero*'
    exclude 'bridges/five-zero*'

    from(nonJar) {
        into("bridges")
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId "com.datastax.cassandra"
            artifactId "cassandra-analytics-core-ext_spark3_${scalaVersion}"
            version = "${project.version}"

            from components.shadow

            // Add dependencies to POM same as Cassandra Analytics Core module,
            // which we have just repackaged.
            pom {
                withXml {
                    def depsNode = asNode().appendNode("dependencies")

                    def resolveDepsForUsage = { usageName ->
                        def cfg = configurations.detachedConfiguration(project.dependencies.create("org.apache.cassandra:cassandra-analytics-core_spark3_${scalaVersion}:${analyticsVersion}"))
                        cfg.attributes {
                            attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, usageName))
                        }
                        return cfg
                    }

                    def collectChildren = {
                        cfg -> cfg.resolvedConfiguration
                                .firstLevelModuleDependencies
                                .iterator()
                                .next()
                                .children
                                .collect { "${it.moduleGroup}:${it.moduleName}:${it.moduleVersion}" }
                                .toSet()
                    }

                    def compileCfg = resolveDepsForUsage(Usage.JAVA_API)
                    def runtimeCfg = resolveDepsForUsage(Usage.JAVA_RUNTIME)
                    def compileDeps = collectChildren(compileCfg)
                    def runtimeDeps = collectChildren(runtimeCfg)

                    compileDeps.each { gav ->
                        def (g, a, v) = gav.split(':')
                        def d = depsNode.appendNode('dependency')
                        d.appendNode('groupId', g)
                        d.appendNode('artifactId', a)
                        d.appendNode('version', v)
                        d.appendNode('scope', 'compile')
                    }

                    (runtimeDeps - compileDeps).each { gav ->
                        def (g, a, v) = gav.split(':')
                        def d = depsNode.appendNode('dependency')
                        d.appendNode('groupId', g)
                        d.appendNode('artifactId', a)
                        d.appendNode('version', v)
                        d.appendNode('scope', 'runtime')
                    }
                }
            }
        }
    }
}

// Disable Gradle Module Metadata publication (dependencies in POM file are added manually)
tasks.withType(GenerateModuleMetadata) {
    enabled = false
}